ACFLAGS += -p ../../src -a ../../src/error_handling/default_stack_trace.ah -a ../../src/bug_detection/nullptr_check.ah -a ../../src/util/default_stack_trace_msg_builder.ah --builtin_operators

include ../Makefile.generic
