ACFLAGS += -p ../../src -a ../../src/error_handling/default_stack_trace.ah -a ../../src/error_detection/error_code_converter.ah -a ../../src/error_handling/default_stack_trace_msg_builder.ah

include ../Makefile.generic
