ACFLAGS += -p ../../src -a ../../src/error_handling/default_stack_trace.ah -a ../../src/error_handling/default_stack_trace_msg_builder.ah #-a ../../src/functionality/synchronization.ah -a ../../src/util/p_thread_controller.ah -a ../../src/bug_detection/nullptr_check.ah --builtin_operators

include ../Makefile.generic
