ACFLAGS += -p ../../src -a ../../src/functionality/default_after_logging.ah -a ../../src/functionality/default_before_logging.ah -a ../../src/util/default_logging_msg_builder.ah

include ../Makefile.generic
